//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.03 at 10:15:56 AM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/collaborator", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.luis.app.cliente.soap.schema;
