//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 08:05:53 PM CDT 
//


package com.luis.app.soap.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.luis.app.soap.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CollaboratorResponse_QNAME = new QName("http://www.example.org/collaborator", "collaboratorResponse");
    private final static QName _CollaboratorRequest_QNAME = new QName("http://www.example.org/collaborator", "collaboratorRequest");
    private final static QName _CollaboratorFault_QNAME = new QName("http://www.example.org/collaborator", "collaboratorFault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.luis.app.soap.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CollaboratorRequest }
     * 
     */
    public CollaboratorRequest createCollaboratorRequest() {
        return new CollaboratorRequest();
    }

    /**
     * Create an instance of {@link CollaboratorDetail }
     * 
     */
    public CollaboratorDetail createCollaboratorDetail() {
        return new CollaboratorDetail();
    }

    /**
     * Create an instance of {@link CollaboratorFault }
     * 
     */
    public CollaboratorFault createCollaboratorFault() {
        return new CollaboratorFault();
    }

    /**
     * Create an instance of {@link CollaboratorResponse }
     * 
     */
    public CollaboratorResponse createCollaboratorResponse() {
        return new CollaboratorResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CollaboratorResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/collaborator", name = "collaboratorResponse")
    public JAXBElement<CollaboratorResponse> createCollaboratorResponse(CollaboratorResponse value) {
        return new JAXBElement<CollaboratorResponse>(_CollaboratorResponse_QNAME, CollaboratorResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CollaboratorRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/collaborator", name = "collaboratorRequest")
    public JAXBElement<CollaboratorRequest> createCollaboratorRequest(CollaboratorRequest value) {
        return new JAXBElement<CollaboratorRequest>(_CollaboratorRequest_QNAME, CollaboratorRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CollaboratorFault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/collaborator", name = "collaboratorFault")
    public JAXBElement<CollaboratorFault> createCollaboratorFault(CollaboratorFault value) {
        return new JAXBElement<CollaboratorFault>(_CollaboratorFault_QNAME, CollaboratorFault.class, null, value);
    }

}
